Modon/Modon.Portal/Controllers/BuildingController.cs
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.DataContracts.Record;
using Modon.CommonDefinitions.Filters;
using PMApp.Core.CommonDefinitions.Filters;
using Modon.Portal.Helpers;
using Modon.Services;
using PMApp.Core.Services;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Modon.DAL6;
using PMApp.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMApp.Core.CommonDefinitions;

namespace Modon.Portal.Controllers
{
    [Authorize]
    public class BuildingController : Controller
    {

        public ActionResult ListBuilding()
        {
            var buildingRecords = GetBuildingList();
            return View(buildingRecords);

        }

        public ActionResult EListBuilding()
        {
            var buildingRecords = GetBuildingList();
            return View(buildingRecords);
        }


        public ActionResult DeleteBuilding(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = new BuildingRecord
           {
               ID = buildingID
           };
            var buildingResponse = buildingService.DoBuildingDelete(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingDeletedSuccessfuly"));
            else
                SessionHelper.Set("FailMessage", buildingResponse.Message);
            return null;
        }

        public ActionResult AddBuilding()
        {
            FillAddBuildingFields();
            return View();
        }

        [HttpPost]
        public ActionResult AddBuilding(BuildingRecord model)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = model;
            var buildingResponse = buildingService.DoBuildingInsert(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingAddedSuccessfuly"));

                return RedirectToAction("ListBuilding");
            }
            SessionHelper.Set("FailMessage", buildingResponse.Message);
            FillAddBuildingFields();
            return View();
        }


        public ActionResult EditBuilding(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.Filter = new BuildingRequestFilter
           {
               IDList = new List<long>() { buildingID }
           };
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            var record = buildingResponse.BuildingRecords[0];
            FillAddBuildingFields(record);
            return View(record);
        }


        public ActionResult BuildingDetails(long buildingID)
        {
            var record = GetBuildingDetails(buildingID);
         ViewBag.comments= GetAllComments(buildingID);
            return View(record);
        }


        public ActionResult EBuildingDetails(long buildingID, long orderID=0)
        {
            var record = GetBuildingDetails(buildingID);
            ViewBag.comments = GetAllComments(buildingID);
            ViewBag.orderID = orderID;
            return View(record);
        }
        public ActionResult EBuildingReview(long buildingID,long orderID)
        {
            var record = GetBuildingDetails(buildingID);
            long orderIDRef=0;
            ViewBag.order = GetOrderDetails(orderID, buildingID, out orderIDRef);
            ViewBag.comments = GetAllComments(orderIDRef, false);

            return View(record);
        }



        public ActionResult MService(long buildingID)
        {
            ViewBag.buildingID = buildingID;
            return PartialView();
        }


        public ActionResult AddBuildingActivity(long pIndex = 0)
        {
            ViewBag.pIndex = pIndex;
            return PartialView();
        }

        [HttpPost]
        public ActionResult EditBuilding(BuildingRecord model)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = model;
            var buildingResponse = buildingService.DoBuildingUpdate(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingEditedSuccessfuly"));

                return RedirectToAction("ListBuilding");
            }
            SessionHelper.Set("FailMessage", buildingResponse.Message);

            FillAddBuildingFields(model);
            return View(model);
        }

        public string ChangeBuildingStatus(long buildingID, long statusID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = new BuildingRecord();
            buildingRequest.BuildingRecord.StatusID = statusID;
            buildingRequest.BuildingRecord.ID = buildingID;
            var buildingResponse = buildingService.DoBuildingUpdate(buildingRequest);
            var msg = ResourceManager.UIGetResource("StatusChangedSuccessfully");
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(msg);
            }
            else
            {
                SessionHelper.SetFailMessage( buildingResponse.Message);
                msg = buildingResponse.Message;
            }

            return msg;
        }


        private void FillAddBuildingFields(BuildingRecord buildingRecord = null)
        {
            var userEXService = new UserExService();
            var areaRequest = RequestBuilder.CreateRequest<AreaRequest, AreaRequestFilter>(User.Identity.Name,
                new AreaRequestFilter
                {
                    //ShowOnlyMyArea = true
                });
            var areaResponse = userEXService.DoAreaList(areaRequest);
            var areasList = areaResponse.AreaRecords.Where(p => p.ParentID == null).ToArray();
            ViewBag.areas = areasList;

            var activityTypeService = new ActivityTypeService();
            var activityTypeRequest = RequestBuilder.CreateRequest<ActivityTypeRequest, ActivityTypeRequestFilter>(User.Identity.Name,
                new ActivityTypeRequestFilter
                {
                    //ShowOnlyMyArea = true
                });
            var activityTypeResponse = activityTypeService.DoActivityTypeList(activityTypeRequest);
            ViewBag.activityType = activityTypeResponse.ActivityTypeRecords.ToArray();


        }

        public JsonResult FillSubActivity(long parentID)
        {
            var activityTypeService = new Activity_SubTypeService();
            var activityTypeRequest = RequestBuilder.CreateRequest<Activity_SubTypeRequest, Activity_SubTypeRequestFilter>(User.Identity.Name,
                new Activity_SubTypeRequestFilter
                {
                    ActivityTypeIDList = new List<long> { parentID }
                });
            var activityTypeResponse = activityTypeService.DoActivity_SubTypeList(activityTypeRequest);
            return Json(activityTypeResponse.Activity_SubTypeRecords);
        }
        private BuildingRecord[] GetBuildingList()
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);

            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            return buildingResponse.BuildingRecords;
        }
        private BuildingRecord GetBuildingDetails(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.Filter = new BuildingRequestFilter
            {
                IDList = new List<long>() { buildingID }
            };
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            return buildingResponse.BuildingRecords[0];
        }

        private Order_CommentRecord[] GetAllComments(long targetID,bool isBuilding=true)
        {
            var order_CommentService = new Order_CommentService();
            var order_CommentRequest = RequestBuilder.CreateRequest<Order_CommentRequest>(User.Identity.Name);
            if (isBuilding)
            order_CommentRequest.Filter = new Order_CommentRequestFilter { BuildingIDList = new List<long> { targetID } };
            else
                order_CommentRequest.Filter = new Order_CommentRequestFilter { OrderIDList = new List<long> { targetID } };

            var order_CommentResponse = order_CommentService.DoOrder_CommentList(order_CommentRequest);
            return order_CommentResponse.Order_CommentRecords;
        }
        private ModonOrderRecord GetOrderDetails(long modonOrderID,long buildingID,out long orderIDRef)
        {

            if(modonOrderID==0)
            {
                //Get Order

            }
            var modonOrderService = new ModonOrderService();

Modon/Modon.Portal/Controllers/ModonOrderController.cs
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.DataContracts.Record;
using Modon.CommonDefinitions.Filters;
using PMApp.Core.CommonDefinitions.Filters;
using Modon.Portal.Helpers;
using Modon.Services;
using PMApp.Core.Services;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Modon.DAL6;
using PMApp.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMApp.Core.CommonDefinitions;

namespace Modon.Portal.Controllers
{
    [Authorize]
    public class ModonOrderController : Controller
    {

        public ActionResult ListModonOrder(long buildingID = 0, bool isPatrial = false)
        {
            ViewBag.isPatrial = isPatrial;
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            if (buildingID > 0)
            {
                modonOrderRequest.Filter = new ModonOrderRequestFilter();
                modonOrderRequest.Filter.BuildingIDList = new List<long> { buildingID };
            }
            var modonOrderResponse = modonOrderService.DoModonOrderList(modonOrderRequest);
            if (isPatrial)
                return PartialView(modonOrderResponse.ModonOrderRecords);
            else
                return View(modonOrderResponse.ModonOrderRecords);
        }
        public ActionResult EListModonOrder(long buildingID = 0, bool isPatrial = false)
        {
            ViewBag.isPatrial = isPatrial;
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            if (buildingID > 0)
            {
                modonOrderRequest.Filter = new ModonOrderRequestFilter();
                modonOrderRequest.Filter.BuildingIDList = new List<long> { buildingID };
            }
            var modonOrderResponse = modonOrderService.DoModonOrderList(modonOrderRequest);
            if (isPatrial)
                return PartialView(modonOrderResponse.ModonOrderRecords);
            else
                return View(modonOrderResponse.ModonOrderRecords);
        }
        public PartialViewResult EPartialModonOrder(ModonOrderRecord[] model)
        {
            return PartialView(model);
        }
        public PartialViewResult PartialModonOrder(ModonOrderRecord[] model)
        {
            return PartialView(model);
        }

        public ActionResult DeleteModonOrder(long modonOrderID)
        {
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            modonOrderRequest.ModonOrderRecord = new ModonOrderRecord
           {
               ID = modonOrderID
           };
            var modonOrderResponse = modonOrderService.DoModonOrderDelete(modonOrderRequest);
            if (modonOrderResponse.Success.HasValue && modonOrderResponse.Success.Value)
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("ModonOrderDeletedSuccessfuly"));
            else
                SessionHelper.Set("FailMessage", modonOrderResponse.Message);
            return null;
        }

        public ActionResult AddModonOrder()
        {
            FillAddModonOrderFields();
            return View();
        }

        [HttpPost]
        public ActionResult AddModonOrder(ModonOrderRecord model)
        {
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            modonOrderRequest.ModonOrderRecord = model;
            var modonOrderResponse = modonOrderService.DoModonOrderInsert(modonOrderRequest);
            if (modonOrderResponse.Success.HasValue && modonOrderResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("ModonOrderAddedSuccessfuly"));

                return RedirectToAction("ListModonOrder");
            }
            SessionHelper.Set("FailMessage", modonOrderResponse.Message);
            FillAddModonOrderFields();
            return View();
        }


        public ActionResult EditModonOrder(long modonOrderID)
        {
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            modonOrderRequest.Filter = new ModonOrderRequestFilter
           {
               IDList = new List<long>() { modonOrderID }
           };
            var modonOrderResponse = modonOrderService.DoModonOrderList(modonOrderRequest);
            var record = modonOrderResponse.ModonOrderRecords[0];
            FillAddModonOrderFields(record);
            return View(record);
        }

        [HttpPost]
        public ActionResult EditModonOrder(ModonOrderRecord model)
        {
            var modonOrderService = new ModonOrderService();
            var modonOrderRequest = RequestBuilder.CreateRequest<ModonOrderRequest>(User.Identity.Name);
            modonOrderRequest.ModonOrderRecord = model;
            var modonOrderResponse = modonOrderService.DoModonOrderUpdate(modonOrderRequest);
            if (modonOrderResponse.Success.HasValue && modonOrderResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("ModonOrderEditedSuccessfuly"));

                return RedirectToAction("ListModonOrder");
            }
            SessionHelper.Set("FailMessage", modonOrderResponse.Message);

            FillAddModonOrderFields(model);
            return View(model);
        }

        private void FillAddModonOrderFields(ModonOrderRecord modonOrderRecord = null)
        {



        }

        public ActionResult BuildingLicence(long buildingID)
        {
            var record = GetBuildingDetails(buildingID);
            return View(record);
        }
        private BuildingRecord GetBuildingDetails(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.Filter = new BuildingRequestFilter
            {
                IDList = new List<long>() { buildingID }
            };
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            return buildingResponse.BuildingRecords[0];
        }


    }
}

Modon/Modon.Portal/Views/Building/AddBuildingActivity.cshtml
<tr>
    <td><select onchange="ddlaOthers(this,'@ViewBag.pIndex')" class="form-control" id="ddlsubActivity_@ViewBag.pIndex" name="BuildingActivities[@ViewBag.pIndex].ActivitSubTypeID"></select><div id="dvaother_@ViewBag.pIndex" hidden> <input name="BuildingActivities[@ViewBag.pIndex].ActivitOtherSubTypeName" class="form-control" value="" id="txtaother_@ViewBag.pIndex" width="80%" /> <i class="fa fa-remove text-danger" onclick="showActivities('@ViewBag.pIndex')">إلغاء</i></div></td>
    <td><input name="IsAllowed" disabled  type="checkbox" data-render="switchery" data-theme="default" data-switchery="true" style="display: none;"></td>
    <td><a onclick='removeProduct(this)' href="#" id="username" data-type="text" data-pk="1">حذف <i class="fa fa-remove text-danger"></i></a></td>

</tr>

Modon/Modon.Portal/Views/Building/EListBuilding.cshtml
@using Modon.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6.EntitiesExtention;
@using PMApp.Core.Helpers;
@using PMApp.Modon.DAL6;
@model BuildingRecord[]

@{
    ViewBag.Title = ResourceManager.UIGetResource("ListBuilding");

}
@{ Layout = "~/Views/Shared/_ELayout.cshtml";}

<div class="search-toolbar">
    <!-- BEGIN row -->
    <div class="row">
        <!-- BEGIN col-6 -->
        <div class="col-md-6">
        </div>
        <!-- END col-6 -->
        <!-- BEGIN col-6 -->
        <div class="col-md-6 text-right f-s-20">
            <i class="fa fa-circle text-success"></i>
            @ViewBag.Title
        </div>
        <!-- END col-6 -->
    </div>
    <!-- END row -->
</div>
<div class="panel panel-default ">

    <div class="panel-body">
        <div class="row">

            <table class="table table-striped table-bordered dataTable no-footer data-table" role="grid" aria-describedby="datatable_info" dir="rtl">
                <thead>
                    <tr>
                        <th class="text-right">@ResourceManager.UIGetResource("BuildingName")</th>
                        <th class="text-right">@ResourceManager.UIGetResource("ActivityTypeName")</th>
                        <th class="text-right">@ResourceManager.UIGetResource("AreaName")</th>
                        <th class="text-right">@ResourceManager.UIGetResource("CreatedByFullName")</th>
                        <th class="text-right">@ResourceManager.UIGetResource("Phone")</th>
                        <th class="text-right">@ResourceManager.UIGetResource("StatusName")</th>
                        <th class="text-right"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.Name</td>
                                <td class="text-primary">@item.ActivityTypeName</td>
                                <td class="text-right">@item.AreaName</td>
                                <td class="text-right">@item.CreatedByFullName</td>
                                <td class="text-right">@item.Phone</td>
                                <td><span class=" badge badge-warning">@ResourceManager.GetUIInstance().GetResource(item.StatusName)  </span></td>
                                <td><a href="@Url.Action("EBuildingDetails", "Building", new { buildingID = item.ID, orderID = 0 })" class=" btn btn-sm btn-success"> @ResourceManager.GetUIInstance().GetResource("BuildingDetails") <i class=" fa fa-refresh  text-white"></i></a>   </td>
                            </tr>
                            }
                </tbody>
            </table>

        </div>
    </div>
</div>

Modon/Modon.Portal/Views/Building/ListBuilding.cshtml
@using Modon.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6.EntitiesExtention;
@using PMApp.Core.Helpers;
@using PMApp.Modon.DAL6;
@model BuildingRecord[]
@{
    ViewBag.Title = ResourceManager.UIGetResource("ListBuilding");
}

    <div class="search-toolbar">
        <!-- BEGIN row -->
        <div class="row">
            <!-- BEGIN col-6 -->
            <div class="col-md-6">
            </div>
            <!-- END col-6 -->
            <!-- BEGIN col-6 -->
            <div class="col-md-6 text-right f-s-20">
                <i class="fa fa-circle text-success"></i>
        @ViewBag.Title
            </div>
            <!-- END col-6 -->
        </div>
        <!-- END row -->
    </div>
    <div class="row">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <div class="product ">
                    <!-- BEGIN product-detail -->
                    <div class="product-detail">
                        <!-- BEGIN product-image -->
                        <!-- END product-image -->
                        <!-- BEGIN product-info -->
                        <div class="product-info">
                            <!-- BEGIN product-info-header -->
                            <div class="product-info-header">
                                <h1 class="product-title text-right " style="font-size:24px">
                                    @if (item.StatusID == ConfigManager.GetUIInstance().Order_ApprovedStatusID)
                                    {
                                        <span class="label label-l label-success "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_ApprovedStatusID_Slogan") </span>
                                    }
                                    else if (item.StatusID == ConfigManager.GetUIInstance().Order_NewStatusID)
                                    {
                                        <span class="label label-warning "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_NewStatusID_Slogan") </span>
                                    }
                                    else if (item.StatusID == ConfigManager.GetUIInstance().Order_PendingForEditStatusID)
                                    {
                                        <span class="label label-info "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_PendingForEditStatusID") </span>
                                    }
                                    else if (item.StatusID == ConfigManager.GetUIInstance().Order_PendingForManagerStatusID)
                                    {
                                        <span class="label label-info "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_PendingForManagerStatusID") </span>
                                    }
                                    else if (item.StatusID == ConfigManager.GetUIInstance().Order_RejectedStatusID)
                                    {
                                        <span class="label label-danger "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_RejectedStatusID_Slogan") </span>
                                    }
                                    @item.Name
                                </h1>

                            </div>
                            <div class="row">
                                <div class="checkout-body ">
                                    <!-- BEGIN checkout-message -->
                                    <div class="checkout-message">
                                        <div class="table-responsive2">
                                            <div class="col-md-6">
                                                <table class="table ">
                                                    <tbody>
                                                        <tr>
                                                            <td width="30%" class="field text-success f-w-700">@ResourceManager.UIGetResource("Email")</td>
                                                            <td class="value "> @item.Email</td>
                                                        </tr>

                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("Phone")</td>
                                                            <td class="value">@item.Phone</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("OwnerName")</td>
                                                            <td class="value"> @item.OwnerName</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("OwnerCID")</td>
                                                            <td class="value">
                                                                @item.OwnerCID
                                                            </td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="col-md-6">
                                                <table class="table ">
                                                    <tbody>
                                                        <tr>
                                                            <td width="30%" class="field text-success f-w-700">@ResourceManager.UIGetResource("ActivityTypeName")</td>
                                                            <td class="value "> @item.ActivityTypeName</td>
                                                        </tr>

                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("AreaName")</td>
                                                            <td class="value">@item.AreaName</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("StreetAdress")</td>
                                                            <td class="value"> @item.StreetAdress</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="field text-success f-w-700">@ResourceManager.UIGetResource("AreaSpace")</td>
                                                            <td class="value">
                                                                @item.AreaSpace
                                                            </td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <hr />
                            <div class="row">
                                <a href="@Url.Action("BuildingDetails", "Building", new { buildingID = item.ID })" class="m-l-15 pull-left"><i class="fa fa-info-circle fa-fw"></i> @ResourceManager.GetUIInstance().GetResource("BuildingDetails")</a>
                                @if (item.StatusID == ConfigManager.GetUIInstance().Order_ApprovedStatusID)
                                {
                                    <a href="@Url.Action("BuildingLicence", "ModonOrder", new { buildingID = item.ID })"><i class="fa fa-plus-circle fa-fw"></i>  طلب إصدار رخصة نهائية</a>
                                }
                            </div>
                        </div>

                    </div>

                </div>

            }
        }
        else
        {
            <ul class="timeline " id="dvwallet" dir="rtl">
                    <li>

                        <!-- begin timeline-time -->
                        <div class="timeline-time">
                            <span class="date text-muted">-</span>
                        </div>
                        <!-- end timeline-time -->
                        <!-- begin timeline-icon -->
                        <div class="timeline-icon ">
                            <a class="bg-white"><i class="fa fa-plus-square fa-fw text-danger"></i></a>

                        </div>
                        <!-- end timeline-icon -->
                        <!-- begin timeline-body -->
                        <div class="timeline-body ">
                            <div class="timeline-header">
                                <span>
                                    <b> لا يوجدة منشآت تم إضافتها حتى الان </b> 
                                </span>
                            </div>
                            <div class="timeline-content">
                                                             <div class="col-md-12">
                               <a class="pull-left" href="@Url.Action("AddBuilding","Building")"><i class="fa fa-plus-circle fa-fw"></i>  إضافة منشأة جديدة</a>

                                </div>


                            </div>
                           
                        </div>
                        <!-- end timeline-body -->
                    </li>
            </ul>
        }

    </div>