Modon/Modon.Portal/Controllers/DashboardController.cs
using Modon.Portal.Controllers;
using System.Web.Mvc;

namespace LiveRep.Portal.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {
        //
        // GET: /Dashboard/
        public ActionResult Welcome()
        {

            return View();
        }

        

        public ActionResult Index()
        {
            return View();
        }
    }
}

Modon/Modon.Portal/Controllers/UserController.cs
using Modon.Portal.Helpers;
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.Filters;
using Modon.Services;
using System.Linq;
using PMApp.Core.CommonDefinitions;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Core.CommonDefinitions.Filters;
using PMApp.Core.Helpers;
using PMApp.Core.Services;
using PMApp.Modon.DAL6;
using PMApp.Modon.DAL6.EntitiesExtention;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using System.Web.Security;


namespace Modon.Portal.Controllers
{
    public class UserController : BaseController
    {

        [HttpPost]
        public ActionResult SocialLogin(UserRecord user)
        {
            var applicationID = ApplicationManager.GetApplicationIDFromAppCode(ConfigManager.DefaultApplicationCode);

            var userService = new UserService();
            //user.RememberMe = true;
            var loginRequest = RequestBuilder.CreateRequest<LoginRequest>("");

            loginRequest.LoginChannelName = ConfigManager.GetInstance(applicationID).WebChannelName;
            loginRequest.DeviceRecord = new DeviceRecord
            {
                DeviceName = ConfigManager.GetInstance(applicationID).WebChannelName,
                //DeviceType = ConfigManager.GetInstance(applicationID).type
            };
            if (string.IsNullOrWhiteSpace(user.Email))
                user.Email = ConfigManager.GetInstance(applicationID).DefaultEmail;
            loginRequest.Email = user.Email.ToLower();
            loginRequest.FacebookUserID = user.FacebookUserID;
            loginRequest.SetApplicationID(applicationID);
            var loginResponse = userService.DoSocialLogin(loginRequest);
            if (loginResponse.Success.HasValue && loginResponse.Success.Value)
            {
                var ApplicationCode = ApplicationManager.GetApplicationFromApplicationID(applicationID);
                var authToken = loginResponse.AuthToken;
                FormsAuthentication.SetAuthCookie(authToken, user.RememberMe);
                UIHelper.CurrentUserID = loginResponse.UserId;
                return null;
            }

            if (loginResponse.Status == ResponseStatus.Inactive.ToString())
            {
                SessionHelper.SetFailMessage(loginResponse.Message);
                return Json(loginResponse.Message);
            }
            FillLookups(applicationID);
            var userRecord = new UserRecord
            {
                Email = user.Email,
                FullName = user.FullName,
                FacebookUserID = user.FacebookUserID,
                RememberMe = user.RememberMe,
                Password = user.Password
            };
            return View("AddUserRegisteration", userRecord);

        }

        public ActionResult Login()
        {
            SessionHelper.ClearCurrentSession();
            SessionHelper.ClearCurrentCache();
            ViewBag.returnUrl = Request.QueryString["ReturnUrl"];
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserRecord model)
        {
            long applicationID = 0;
            if (model.ApplicationID > 0)
            {
                applicationID = model.ApplicationID;
                model.ApplicationCode = ApplicationManager.GetApplicationFromApplicationID(applicationID);
            }
            else
                applicationID = ApplicationManager.GetApplicationIDFromAppCode(model.ApplicationCode);
            if (applicationID > 0)
            {
                var userService = new UserService();
                var loginRequest = RequestBuilder.CreateRequest<LoginRequest>("");

                loginRequest.ApplicationCode = model.ApplicationCode;
                loginRequest.LoginChannelName = ConfigManager.GetInstance(applicationID).WebChannelName;
                loginRequest.DeviceRecord = new DeviceRecord
                {
                    DeviceName = ConfigManager.GetInstance(applicationID).WebChannelName,
                    //DeviceType = ConfigManager.GetInstance(applicationID).type
                };

                loginRequest.Email = model.Email;
                loginRequest.FacebookUserID = model.FacebookUserID;
                loginRequest.Password = model.Password;
                loginRequest.SetApplicationID(applicationID);
                var loginResponse = userService.DoLogin(loginRequest);

                if (loginResponse.Success.HasValue && loginResponse.Success.Value)
                {
                    var authToken = loginResponse.AuthToken;
                    FormsAuthentication.SetAuthCookie(authToken, model.RememberMe);
                    UIHelper.CurrentUserID = loginResponse.UserId;

                    if (string.IsNullOrWhiteSpace(model.ReturnUrl))
                    {
                        if (ConfigManager.GetInstance(applicationID).InvestorRoleID == loginResponse.RoleId)
                            return RedirectToAction("Index", "Home", new { application = model.ApplicationCode });
                        else
                            return RedirectToAction("EIndex", "Home", new { application = model.ApplicationCode });

                    }
                    else
                        return Redirect(model.ReturnUrl);
                }
                else
                {
                    ModelState.AddModelError("CredentialError", loginResponse.Message);
                    SessionHelper.SetFailMessage(loginResponse.Message);


                }
            }
            else
            {
                ModelState.AddModelError("CredentialError", ResourceManager.UIGetResource("ErrorInOrganizationCode"));
            }
            return View();
        }

        [Authorize]
        public ActionResult Logout()
        {
            var userID = SecurityHelper.GetUserIDFromAuthenticationToken(User.Identity.Name);
            var userService = new UserService();
            var logoutRequest = RequestBuilder.CreateRequest<LogoutRequest>(User.Identity.Name);

            logoutRequest.UserID = userID;
            var logoutResponse = userService.DoLogout(logoutRequest);
            SessionHelper.ClearCurrentSession();
            SessionHelper.ClearCurrentCache();
            UIHelper.CurrentUserID = 0;
            FormsAuthentication.SignOut();

            return RedirectToAction("Login", "User");
        }

        public ActionResult ForgetPassword(string email)
        {
            var userRecord = new UserRecord();
            return View(userRecord);
        }

        [HttpPost]
        public ActionResult ForgetPassword(UserRecord model)
        {
            var userService = new UserService();
            var forgetPasswordRequest = RequestBuilder.CreateRequest<ForgetPasswordRequest>("");
            forgetPasswordRequest.Email = model.Email;
            var forgetPasswordResponse = userService.DoForgetPassword(forgetPasswordRequest);
            if (forgetPasswordResponse.Success.HasValue && forgetPasswordResponse.Success.Value)
            {
                ViewBag.fullEmail = forgetPasswordResponse.OriginalEmail;
                if (!string.IsNullOrWhiteSpace(forgetPasswordResponse.Email))
                    ViewBag.Email = forgetPasswordResponse.Email;
                if (!string.IsNullOrWhiteSpace(forgetPasswordResponse.SecondEmail))
                    ViewBag.SecondEmail = forgetPasswordResponse.SecondEmail;
                if (!string.IsNullOrWhiteSpace(forgetPasswordResponse.Mobile))
                    ViewBag.Mobile = forgetPasswordResponse.Mobile;

            }
            else
                ViewBag.RegisterationFaild = forgetPasswordResponse.Message;
            return View();

        }

        public ActionResult ForgetPasswordChoice()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgetPasswordChoice(UserRecord model)
        {
            var userService = new UserService();
            var forgetPasswordRequest = RequestBuilder.CreateRequest<ForgetPasswordRequest>("");
            forgetPasswordRequest.Email = model.Email;
            //forgetPasswordRequest.ForgetPasswordChoice = model.ForgetPasswordChoice;
            var forgetPasswordResponse = userService.DoForgetPasswordChoice(forgetPasswordRequest);
            if (forgetPasswordResponse.Success.HasValue && forgetPasswordResponse.Success.Value)
            {
                ViewBag.RegisterationSuccess = forgetPasswordResponse.Message;
            }
            else
                ViewBag.RegisterationFaild = forgetPasswordResponse.Message;
            return RedirectToAction("Login");

        }

        #region Backend Users
        [Authorize]
        public ActionResult AddUser()
        {
            FillLookups(1);

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddUser(UserRecord model)
        {
            var userService = new UserService();
            var userRequest = RequestBuilder.CreateRequest<UserRequest>(User.Identity.Name);
            userRequest.UserRecord = model;
            var userResponse = userService.DoUserInsertOperation(userRequest);
            if (userResponse.Success.HasValue && userResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(userResponse.Message);

                return RedirectToAction("ListUserRegisteration");
            }
            else
                SessionHelper.SetFailMessage(userResponse.Message);
            FillLookups(1, model);
            return View();
        }

        [Authorize]
        public ActionResult ListUser(int pageIndex = 0, int pageSize = 10, string userName = "")
        {
            var userService = new UserService();
            var userRequest = RequestBuilder.CreateRequest<UserRequest>(User.Identity.Name);

Modon/Modon.Portal/Views/User/ActivateAccount.cshtml
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6;
@using PMApp.Modon.DAL6.EntitiesExtention;
@model  UserRecord
@{ Layout = "~/Views/Shared/_AnonimusLayout.cshtml";}
@{
    ViewBag.Title = ResourceManager.UIGetResource("ActivateAccountPage");
}
<div id="page-container" class="fade">
    <!-- begin login -->
    <div class="login login-with-news-feed">
        <!-- begin news-feed -->
        <div class="news-feed">
            <div class="news-image">
                <img src="~/assets/img/login-bg.jpeg" data-id="login-cover-image" alt="" />
            </div>
            <div class="news-caption ">
                <h6 class="caption-title pull-right"><i class="fa fa-edit text-success pull-right"></i>  مدن لترخيص ورقابة وتقييم المنشآت فى المدن الصناعية الرئيسية</h6>
                <p class="pull-right" style="text-align:right">
                </p>
                <br />
                <div class="btn-group">
                    <button type="button" style="min-width:150px" class="btn btn-danger btn-filter f-s-16" data-target="pagado">غير مستوفية</button>
                    <button type="button" style="min-width:150px" class="btn btn-warning btn-filter f-s-16" data-target="pendiente">مستوفية بشروك</button>
                    <button type="button" style="min-width:150px" class="btn bg-yellow btn-filter f-s-16" data-target="cancelado">مستوفية بشروط</button>
                    <button type="button" style="min-width:150px" class="btn btn-success btn-filter f-s-16" data-target="cancelado">مستوفية</button>

                    <button type="button" style="min-width:150px" class="btn btn-default btn-filter f-s-16" data-target="all">ممتاز</button>
                </div>
            </div>
        </div>
        <!-- end news-feed -->
        <!-- begin right-content -->
        <div class="right-content">
            <!-- begin login-header -->
            <div class="login-header">
                <div class="brand">
                    <img src="~/assets/img/logo.png" width="80" height="100" />

                </div>
                <div class="icon">
                    <i class="fa fa-sign-in"></i>
                </div>
            </div>
            <!-- end login-header -->
            <!-- begin login-content -->
            <div class="login-content">
                <form method="post" action="ActivateAccount" class="form-horizontal form-label-left">
                    <div class="form-group m-b-20">
                        @Html.TextBoxFor(model => model.Email, new { @placeholder = ResourceManager.UIGetResource("Email"), @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "validation-message" })
                    </div>
                    <div class="form-group m-b-20">
                        @Html.TextBoxFor(model => model.Code, new { @placeholder = ResourceManager.UIGetResource("ActivationCode"), @class = "form-control col-md-7 col-xs-12" })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "validation-message" })
                    </div>
                    <div class="login-buttons">
                        <button type="submit" class="btn btn-success btn-block btn-lg">@ResourceManager.UIGetResource("Activate")</button>
                    </div>
                </form>
            </div>
            <!-- end login-content -->
        </div>
        <!-- end right-container -->
    </div>
    <!-- end login -->
</div>
<div class="modal fade" id="modal-alert">
    <div class="modal-dialog">
        <div class="modal-content">
            
            <div class="modal-body">
                <div class="col-lg-12">
                    <div class="box">
                        <div class="icon">
                            <div class="imagered"><i class="fa fa-thumbs-o-down"></i></div>
                            <div class="info">
                                <h3 class="title">@ResourceManager.UIGetResource("Failed")</h3>
                                <p>
                                    @if (ViewBag.ActivationFaild != null)
                                    {
                                        @ViewBag.ActivationFaild
                                    }
                                </p>
                            </div>
                        </div>
                        <div class="space"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-sm btn-blue-grey" data-dismiss="modal">@ResourceManager.UIGetResource("Close")</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-success">
    <div class="modal-dialog">
        <div class="modal-content">
           
            <div class="modal-body">
                <div class="col-lg-12">
                    <div class="box">
                        <div class="icon">
                            <div class="image"><i class="fa fa-thumbs-o-up"></i></div>
                            <div class="info">
                                <h3 class="title">@ResourceManager.UIGetResource("Success")</h3>
                                <p>
                                    @if (ViewBag.ActivationSuccess != null)
                                    {
                                      @ViewBag.ActivationSuccess  
                                    }
                                </p>
                            </div>
                        </div>
                        <div class="space"></div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a href="~/@ApplicationManager.GetApplicationFromRouteData()/Home/Index" class="btn btn-sm btn-success">@ResourceManager.UIGetResource("GoToHomePage")</a>
            </div>
        </div>
    </div>
</div>


@if (ViewBag.ActivationFaild != null)
{
    <script>
        $(document).ready(function () {
            $('#modal-alert').modal('show');
        });
    </script>
    ViewBag.ActivationFaild = null;
}
@if (ViewBag.ActivationSuccess != null)
{
    <script>
        $(document).ready(function () {
            $('#modal-success').modal({ backdrop: 'static', keyboard: false });
        });
    </script>
    ViewBag.ActivationSuccess = null;
}

Modon/Modon.Portal/Views/User/AddUser.cshtml
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6;
@using Modon.CommonDefinitions.DataContracts.Record;
@model UserRecord
<link href="~/Content/jstree.min.css" rel="stylesheet" />
@{
    ViewBag.Title = ResourceManager.UIGetResource("AddPaymentAccountPaypal");
}
<style>
    .jstree-anchor {
        color: white;
    }
</style>
<div id="content" class="content">
    <h1 class="page-header">
        @ViewBag.Title
    </h1>
    <form action="AddUser" method="post" class="col-md-8 col-md-offset-2">
        <div class="page-title">
            <div class="title_left">
                <h3>@ResourceManager.UIGetResource("EditUser")</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_content">
                        <div class="row demo-container">
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("FullName")
                                </label>
                                <div>
                                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "validation-message" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Email")
                                </label>
                                <div>
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "validation-message" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("phone1")
                                </label>
                                <div>
                                    @Html.TextBoxFor(model => model.phone1, new { @placeholder = ResourceManager.UIGetResource("Mobile"), @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.phone1, "", new { @class = "validation-message" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Password")
                                </label>
                                <div>
                                    <input class="form-control col-md-7 col-xs-12" type="password" name="Password" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("ReTypePassword")
                                </label>
                                <div>
                                    @Html.PasswordFor(model => model.VerifiedPassword, new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.VerifiedPassword, "", new { @class = "validation-message" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Role")
                                </label>
                                <div>
                                    @Html.DropDownListFor(model => model.RoleID, new SelectList((ApplicationRoleRecord[])@ViewBag.role, "ID", "Name"), @ResourceManager.UIGetResource("ChooseRole"), new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.RoleID, "", new { @class = "validation-message" })
                                </div>
                            </div>
                            @*<div class="form-group">
                                    @Html.DropDownListFor(model => model.AreaID, new SelectList((Modon.CommonDefinitions.DataContracts.Record.AreaRecord[])@ViewBag.Areas, "ID", "Name"), @ResourceManager.UIGetResource("ChooseArea"), new { @class = "form-control col-md-7 col-xs-12" })
                                    @Html.ValidationMessageFor(model => model.AreaID, "", new { @class = "validation-message" })
                                </div>*@


                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("IsActive")
                                </label>
                                <div>
                                    <input type="checkbox"  data-render="switchery" data-theme="green" />
                                    @*@Html.CheckBoxFor(model => Model.IsActive, new { @class = "flat" })*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Area"):
                                </label>
                                <div id="jstree">

                                </div>
                            </div>


                            <input hidden name="AreaID" value="0" />
                            <input type="submit" class="btn btn-success btn-block" value="@ResourceManager.UIGetResource("Add")" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<!--include the minified jstree source -->
<script src="~/Scripts/jstree.min.js"></script>
<script>
        $(function () {
            FormSliderSwitcher.init();

        var model=@Html.Raw(Json.Encode(ViewBag.Areas));
        // 6 create an instance when the DOM is ready
        $('#jstree').jstree({
            'core': {
                'data': model.Data,
                "themes" : {
                    "variant" : "large"
                }
            }
        });
        // 7 bind to events triggered on the tree
        $('#jstree').on("changed.jstree", function (e, data) {
            $("[name=AreaID]").val(data.selected);
        });
    });
</script>

Modon/Modon.Portal/Views/User/AssignClients.cshtml
@using PMApp.Modon.DAL6;
@using Modon.CommonDefinitions.DataContracts.Record;
@model ClientRecord[]
<form action="AssignClients" method="post">
    <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
        <thead>
            <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                    @ResourceManager.UIGetResource("Name")
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                    @ResourceManager.UIGetResource("Class")
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                    @ResourceManager.UIGetResource("Type")
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                    @ResourceManager.UIGetResource("Notes")
                </th>

                <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                    @ResourceManager.UIGetResource("IsAssigned")
                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr role="row">
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.ClassName
                    </td>
                    <td>
                        @item.TypeName
                    </td>
                    <td>
                        @item.Notes
                    </td>

                    <td>
                        <input type="checkbox" name="AssignedClientsIDs" value="@item.ID" class="flat" checked="@item.IsAssignedToRequestUser" />

                    </td>
                </tr>
            }
        </tbody>
    </table>
    <input hidden value="@ViewBag.userID" name="userID" />
    <input type="submit" class="btn btn-primary" value="@ResourceManager.UIGetResource("Done")" />

    <script>
    $(document).ready(function () {
        $('#datatable').DataTable({
            "lengthMenu": [[10, 25, 50, -1], ["Display 10", "Display 25", "Display 50", "All"]]
        });
    });
    </script>
</form>

Modon/Modon.Portal/Views/User/Team.cshtml
@using PMApp.Modon.DAL6;
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@model UserRecord[]

    @if (Model != null)
    {
       
                <div class="page-title">
                    <div class="title_left">
                        <h3>@ResourceManager.UIGetResource("MyTeam")</h3>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <div class="row demo-container">
                                    @foreach (var item in Model)
                                    {

                                        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 profile_details">
                                            <div class="well profile_view">
                                                <div class="col-sm-12">
                                                    <h4 class="brief"><i>@item.FullName</i></h4>
                                                    <div class="left col-xs-7">
                                                        <ul class="list-unstyled">
                                                            <li><i class="fa fa-building"></i> Area:@item.AreaName </li>
                                                            <li><i class="fa fa-calendar"></i> BirthDate:@item.Birthdate </li>
                                                        </ul>
                                                    </div>
                                                    <div class="right col-xs-5 text-center">
                                                        <img src="@item.ProfilePictureUrl" alt="" style="width:120px;height:120px" class="img-thumbnail">
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 bottom text-center">

                                                    <div class="col-xs-12 col-sm-6 emphasis">
                                                            <a href="@Url.Action("Index", "Profile", new { userID = item.ID })" class="btn btn-success btn-xs">
                                                                <i class="fa fa-user">
                                                                </i> <i class="fa fa-comments-o"></i>
                                                                profile
                                                            </a>  
                                                        <a href="@Url.Action("Index", "Dashboard", new { userID = item.ID })" class="btn btn-primary btn-xs">
                                                            <i class="fa fa-archive"> </i> @ResourceManager.UIGetResource("Dashboard")
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
         
    }