Modon/Modon.Portal/Controllers/BuildingController.cs
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.DataContracts.Record;
using Modon.CommonDefinitions.Filters;
using PMApp.Core.CommonDefinitions.Filters;
using Modon.Portal.Helpers;
using Modon.Services;
using PMApp.Core.Services;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Modon.DAL6;
using PMApp.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMApp.Core.CommonDefinitions;

namespace Modon.Portal.Controllers
{
    [Authorize]
    public class BuildingController : Controller
    {

        public ActionResult ListBuilding()
        {
            var buildingRecords = GetBuildingList();
            return View(buildingRecords);

        }

        public ActionResult EListBuilding()
        {
            var buildingRecords = GetBuildingList();
            return View(buildingRecords);
        }


        public ActionResult DeleteBuilding(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = new BuildingRecord
           {
               ID = buildingID
           };
            var buildingResponse = buildingService.DoBuildingDelete(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingDeletedSuccessfuly"));
            else
                SessionHelper.Set("FailMessage", buildingResponse.Message);
            return null;
        }

        public ActionResult AddBuilding()
        {
            FillAddBuildingFields();
            return View();
        }

        [HttpPost]
        public ActionResult AddBuilding(BuildingRecord model)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = model;
            var buildingResponse = buildingService.DoBuildingInsert(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingAddedSuccessfuly"));

                return RedirectToAction("ListBuilding");
            }
            SessionHelper.Set("FailMessage", buildingResponse.Message);
            FillAddBuildingFields();
            return View();
        }


        public ActionResult EditBuilding(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.Filter = new BuildingRequestFilter
           {
               IDList = new List<long>() { buildingID }
           };
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            var record = buildingResponse.BuildingRecords[0];
            FillAddBuildingFields(record);
            return View(record);
        }


        public ActionResult BuildingDetails(long buildingID)
        {
            var record = GetBuildingDetails(buildingID);
         ViewBag.comments= GetAllComments(buildingID);
            return View(record);
        }


        public ActionResult EBuildingDetails(long buildingID, long orderID=0)
        {
            var record = GetBuildingDetails(buildingID);
            ViewBag.comments = GetAllComments(buildingID);
            ViewBag.orderID = orderID;
            return View(record);
        }
        public ActionResult EBuildingReview(long buildingID,long orderID)
        {
            var record = GetBuildingDetails(buildingID);
            long orderIDRef=0;
            ViewBag.order = GetOrderDetails(orderID, buildingID, out orderIDRef);
            ViewBag.comments = GetAllComments(orderIDRef, false);

            return View(record);
        }



        public ActionResult MService(long buildingID)
        {
            ViewBag.buildingID = buildingID;
            return PartialView();
        }


        public ActionResult AddBuildingActivity(long pIndex = 0)
        {
            ViewBag.pIndex = pIndex;
            return PartialView();
        }

        [HttpPost]
        public ActionResult EditBuilding(BuildingRecord model)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = model;
            var buildingResponse = buildingService.DoBuildingUpdate(buildingRequest);
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("BuildingEditedSuccessfuly"));

                return RedirectToAction("ListBuilding");
            }
            SessionHelper.Set("FailMessage", buildingResponse.Message);

            FillAddBuildingFields(model);
            return View(model);
        }

        public string ChangeBuildingStatus(long buildingID, long statusID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.BuildingRecord = new BuildingRecord();
            buildingRequest.BuildingRecord.StatusID = statusID;
            buildingRequest.BuildingRecord.ID = buildingID;
            var buildingResponse = buildingService.DoBuildingUpdate(buildingRequest);
            var msg = ResourceManager.UIGetResource("StatusChangedSuccessfully");
            if (buildingResponse.Success.HasValue && buildingResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(msg);
            }
            else
            {
                SessionHelper.SetFailMessage( buildingResponse.Message);
                msg = buildingResponse.Message;
            }

            return msg;
        }


        private void FillAddBuildingFields(BuildingRecord buildingRecord = null)
        {
            var userEXService = new UserExService();
            var areaRequest = RequestBuilder.CreateRequest<AreaRequest, AreaRequestFilter>(User.Identity.Name,
                new AreaRequestFilter
                {
                    //ShowOnlyMyArea = true
                });
            var areaResponse = userEXService.DoAreaList(areaRequest);
            var areasList = areaResponse.AreaRecords.Where(p => p.ParentID == null).ToArray();
            ViewBag.areas = areasList;

            var activityTypeService = new ActivityTypeService();
            var activityTypeRequest = RequestBuilder.CreateRequest<ActivityTypeRequest, ActivityTypeRequestFilter>(User.Identity.Name,
                new ActivityTypeRequestFilter
                {
                    //ShowOnlyMyArea = true
                });
            var activityTypeResponse = activityTypeService.DoActivityTypeList(activityTypeRequest);
            ViewBag.activityType = activityTypeResponse.ActivityTypeRecords.ToArray();


        }

        public JsonResult FillSubActivity(long parentID)
        {
            var activityTypeService = new Activity_SubTypeService();
            var activityTypeRequest = RequestBuilder.CreateRequest<Activity_SubTypeRequest, Activity_SubTypeRequestFilter>(User.Identity.Name,
                new Activity_SubTypeRequestFilter
                {
                    ActivityTypeIDList = new List<long> { parentID }
                });
            var activityTypeResponse = activityTypeService.DoActivity_SubTypeList(activityTypeRequest);
            return Json(activityTypeResponse.Activity_SubTypeRecords);
        }
        private BuildingRecord[] GetBuildingList()
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);

            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            return buildingResponse.BuildingRecords;
        }
        private BuildingRecord GetBuildingDetails(long buildingID)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest>(User.Identity.Name);
            buildingRequest.Filter = new BuildingRequestFilter
            {
                IDList = new List<long>() { buildingID }
            };
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            return buildingResponse.BuildingRecords[0];
        }

        private Order_CommentRecord[] GetAllComments(long targetID,bool isBuilding=true)
        {
            var order_CommentService = new Order_CommentService();
            var order_CommentRequest = RequestBuilder.CreateRequest<Order_CommentRequest>(User.Identity.Name);
            if (isBuilding)
            order_CommentRequest.Filter = new Order_CommentRequestFilter { BuildingIDList = new List<long> { targetID } };
            else
                order_CommentRequest.Filter = new Order_CommentRequestFilter { OrderIDList = new List<long> { targetID } };

            var order_CommentResponse = order_CommentService.DoOrder_CommentList(order_CommentRequest);
            return order_CommentResponse.Order_CommentRecords;
        }
        private ModonOrderRecord GetOrderDetails(long modonOrderID,long buildingID,out long orderIDRef)
        {

            if(modonOrderID==0)
            {
                //Get Order

            }
            var modonOrderService = new ModonOrderService();

Modon/Modon.Portal/Controllers/T_WorkerController.cs
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.DataContracts.Record;
using Modon.CommonDefinitions.Filters;
using PMApp.Core.CommonDefinitions.Filters;
using Modon.Portal.Helpers;
using Modon.Services;
using PMApp.Core.Services;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Modon.DAL6;
using PMApp.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMApp.Core.CommonDefinitions;

namespace Modon.Portal.Controllers
{
    [Authorize]
    public class T_WorkerController : Controller
    {

        public ActionResult ListT_Worker(long buildingID=0)
        {
            var t_WorkerService = new T_WorkerService();
            var t_WorkerRequest = RequestBuilder.CreateRequest<T_WorkerRequest>(User.Identity.Name);
            if (buildingID != 0)
                t_WorkerRequest.Filter = new T_WorkerRequestFilter { BuildingIDList = new List<long?> { buildingID } };
            var t_WorkerResponse = t_WorkerService.DoT_WorkerList(t_WorkerRequest);
            return PartialView(t_WorkerResponse.T_WorkerRecords.Where(p => p.CreatedBy == t_WorkerRequest.UserID).ToArray());
        }

        public ActionResult DeleteT_Worker(long t_WorkerID)
        {
            var t_WorkerService = new T_WorkerService();
            var t_WorkerRequest = RequestBuilder.CreateRequest<T_WorkerRequest>(User.Identity.Name);
            t_WorkerRequest.T_WorkerRecord = new T_WorkerRecord
            {
                ID = t_WorkerID
            };
            var t_WorkerResponse = t_WorkerService.DoT_WorkerDelete(t_WorkerRequest);
            if (t_WorkerResponse.Success.HasValue && t_WorkerResponse.Success.Value)
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("T_WorkerDeletedSuccessfuly"));
            else
                SessionHelper.Set("FailMessage", t_WorkerResponse.Message);
            return null;
        }

        public ActionResult AddT_Worker()
        {
            FillAddT_WorkerFields();
            return View();
        }

        [HttpPost]
        public ActionResult AddT_Worker(T_WorkerRecord model)
        {
            var t_WorkerService = new T_WorkerService();
            var t_WorkerRequest = RequestBuilder.CreateRequest<T_WorkerRequest>(User.Identity.Name);
            t_WorkerRequest.T_WorkerRecord = model;
            var t_WorkerResponse = t_WorkerService.DoT_WorkerInsert(t_WorkerRequest);
            if (t_WorkerResponse.Success.HasValue && t_WorkerResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("T_WorkerAddedSuccessfuly"));

                return RedirectToAction("ListT_Worker");
            }
            SessionHelper.Set("FailMessage", t_WorkerResponse.Message);
            FillAddT_WorkerFields();
            return View();
        }


        public ActionResult EditT_Worker(long t_WorkerID)
        {
            var t_WorkerService = new T_WorkerService();
            var t_WorkerRequest = RequestBuilder.CreateRequest<T_WorkerRequest>(User.Identity.Name);
            t_WorkerRequest.Filter = new T_WorkerRequestFilter
            {
                IDList = new List<long>() { t_WorkerID }
            };
            var t_WorkerResponse = t_WorkerService.DoT_WorkerList(t_WorkerRequest);
            var record = t_WorkerResponse.T_WorkerRecords[0];
            FillAddT_WorkerFields(record);
            return View(record);
        }




        [HttpPost]
        public ActionResult EditT_Worker(T_WorkerRecord model)
        {
            var t_WorkerService = new T_WorkerService();
            var t_WorkerRequest = RequestBuilder.CreateRequest<T_WorkerRequest>(User.Identity.Name);
            t_WorkerRequest.T_WorkerRecord = model;
            var t_WorkerResponse = t_WorkerService.DoT_WorkerUpdate(t_WorkerRequest);
            if (t_WorkerResponse.Success.HasValue && t_WorkerResponse.Success.Value)
            {
                SessionHelper.Set("SuccessMessage", ResourceManager.UIGetResource("T_WorkerEditedSuccessfuly"));

                return RedirectToAction("ListT_Worker");
            }
            SessionHelper.Set("FailMessage", t_WorkerResponse.Message);

            FillAddT_WorkerFields(model);
            return View(model);
        }

        private void FillAddT_WorkerFields(T_WorkerRecord t_WorkerRecord = null)
        {
            var buildingService = new BuildingService();
            var buildingRequest = RequestBuilder.CreateRequest<BuildingRequest, BuildingRequestFilter>(User.Identity.Name,
                new BuildingRequestFilter
                {
                    //ShowOnlyMyArea = true
                });
            var buildingResponse = buildingService.DoBuildingList(buildingRequest);
            var buildingList = buildingResponse.BuildingRecords.Where(p => p.CreatedBy == buildingRequest.UserID && p.StatusName == "Approved").ToArray();

            ViewBag.buildingList = buildingList;



        }
    }
}

Modon/Modon.Portal/Views/Home/Index.cshtml
@using PMApp.Modon.DAL6;
@using Modon.CommonDefinitions.DataContracts.Record
@using Modon.CommonDefinitions.DataContracts.Record
@model BuildingRecord[]


@{
    ViewBag.Title = @ResourceManager.UIGetResource("Dashboard");
}
        <div class="search-toolbar">
            <!-- BEGIN row -->
            <div class="row">
                <!-- BEGIN col-6 -->
                <div class="col-md-6">
                    <a href="@Url.Action("AddBuilding","Building")" class="btn btn-success btn-lg m-b-10 pull-left">إضافة منشأة جديدة <i class="fa fa-plus"></i></a>

                </div>
                <!-- END col-6 -->
                <!-- BEGIN col-6 -->
                <div class="col-md-6 text-right f-s-20">
                    <i class="fa fa-circle text-success"></i>     المنشآت 
                </div>
                <!-- END col-6 -->
            </div>
            <!-- END row -->
        </div>
       
        <!-- end page-header -->
        <div class="row" dir="rtl">
            <div class="col-md-12 ">
                <div class="panel panel-default ">
                    
                    <div class="panel-body">
                        @if (Model != null && Model.Count() > 0)
    {
                        foreach (var item in Model)
                        {
                            <div class="product ">
                                <!-- BEGIN product-detail -->
                                <div class="product-detail">
                                    <!-- BEGIN product-image -->
                                    <!-- END product-image -->
                                    <!-- BEGIN product-info -->
                                    <div class="product-info">
                                        <!-- BEGIN product-info-header -->
                                        <div class="product-info-header">
                                            <h1 class="product-title text-right " style="font-size:24px">
                                                @if (item.StatusID == ConfigManager.GetUIInstance().Order_ApprovedStatusID)
                                                {
                                                    <span class="label label-l label-success "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_ApprovedStatusID_Slogan") </span>
                                                }
                                                else if (item.StatusID == ConfigManager.GetUIInstance().Order_NewStatusID)
                                                {
                                                    <span class="label label-warning "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_NewStatusID_Slogan") </span>
                                                }
                                                else if (item.StatusID == ConfigManager.GetUIInstance().Order_PendingForEditStatusID)
                                                {
                                                    <span class="label label-info "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_PendingForEditStatusID") </span>
                                                }
                                                else if (item.StatusID == ConfigManager.GetUIInstance().Order_PendingForManagerStatusID)
                                                {
                                                    <span class="label label-info "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_PendingForManagerStatusID") </span>
                                                }
                                                else if (item.StatusID == ConfigManager.GetUIInstance().Order_RejectedStatusID)
                                                {
                                                    <span class="label label-danger "><i class="fa fa-building-o"></i><br />@ResourceManager.UIGetResource("Order_RejectedStatusID_Slogan") </span>
                                                }
                                                @item.Name
                                            </h1>

                                        </div>
                                        <div class="row">
                                            <div class="checkout-body ">
                                                <!-- BEGIN checkout-message -->
                                                <div class="checkout-message">
                                                    <div class="table-responsive2">
                                                        <div class="col-md-6">
                                                            <table class="table ">
                                                                <tbody>
                                                                    <tr>
                                                                        <td width="30%" class="field text-success">@ResourceManager.UIGetResource("Email")</td>
                                                                        <td class="value "> @item.Email</td>
                                                                    </tr>

                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("Phone")</td>
                                                                        <td class="value">@item.Phone</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("OwnerName")</td>
                                                                        <td class="value"> @item.OwnerName</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("OwnerCID")</td>
                                                                        <td class="value">
                                                                            @item.OwnerCID
                                                                        </td>
                                                                    </tr>

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <table class="table ">
                                                                <tbody>
                                                                    <tr>
                                                                        <td width="30%" class="field text-success">@ResourceManager.UIGetResource("ActivityTypeName")</td>
                                                                        <td class="value "> @item.ActivityTypeName</td>
                                                                    </tr>

                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("AreaName")</td>
                                                                        <td class="value">@item.AreaName</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("StreetAdress")</td>
                                                                        <td class="value"> @item.StreetAdress</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="field text-success">@ResourceManager.UIGetResource("AreaSpace")</td>
                                                                        <td class="value">
                                                                            @item.AreaSpace
                                                                        </td>
                                                                    </tr>

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <hr />
                                        <div class="row">
                                            <a href="@Url.Action("BuildingDetails", "Building", new { buildingID = item.ID })" class="m-l-15 pull-left"><i class="fa fa-info-circle fa-fw"></i> @ResourceManager.GetUIInstance().GetResource("BuildingDetails")</a>
                                            <a href="@Url.Action("BuildingLicence", "ModonOrder", new { buildingID = item.ID })"><i class="fa fa-plus-circle fa-fw"></i>  طلب إصدار رخصة نهائية</a>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        }

}

                    @*<ul class="popular-tags">
        <li><a href="#"><i class="fa fa-circle text-danger"></i> CSS</a></li>
        <li><a href="#"><i class="fa fa-circle text-primary"></i> Bootstrap</a></li>
        <li><a href="#"><i class="fa fa-circle text-warning"></i> Javascript</a></li>
        <li><a href="#"><i class="fa fa-circle"></i> jQuery</a></li>
        <li><a href="#"><i class="fa fa-circle text-success"></i> Android</a></li>
        <li><a href="#"><i class="fa fa-circle text-muted"></i> iOS</a></li>
        <li><a href="#"><i class="fa fa-circle text-purple"></i> Template</a></li>
    </ul>*@
else
{
                    <div class="col-md-12">
                        <center> <i class="fa fa-2x text-success fa-info-circle"></i></center>
                        <br />
                        <center> <h2>ليس لديك منشأت معتمدة ،، قم بإضافة منشأة للإستفادة من جميع خدماتنا</h2></center>
                        <br />
                    </div>
}

                    </div>
                </div>
            </div>
        </div>
        <div class="search-toolbar">
            <!-- BEGIN row -->
            <div class="row">
                <!-- BEGIN col-6 -->
                <div class="col-md-6">
                    <a href="@Url.Action("AddT_Worker", "T_Worker")" class="btn btn-success btn-lg m-b-10 pull-left">إضافة عامل جديد <i class="fa fa-plus"></i></a>

                </div>
                <!-- END col-6 -->
                <!-- BEGIN col-6 -->
                <div class="col-md-6 text-right f-s-20">
                    <i class="fa fa-circle text-success"></i>    العمالة 
                </div>
                <!-- END col-6 -->
            </div>
            <!-- END row -->
        </div>
        <!-- end page-header -->
        <div class="row" dir="rtl">
            <div class="col-md-12 ">
                <div class="panel panel-default ">
                    <div class="panel-body">
                        <div class="col-md-12">
                            @*<center> <i class="fa fa-2x text-success fa-info-circle"></i></center>
                            <br />
                            <center><h4>ليس لديك عمالة مضافة ،، قم بإضافة عمالة للإستفادة من جميع خدماتنا</h4></center>
                            <br />*@
                            @Html.Action("ListT_Worker", "T_Worker")
                        </div>


                    </div>
                </div>
            </div>

        </div>

Modon/Modon.Portal/Views/Home/LoadRankedUsers.cshtml
@using PMApp.Modon.DAL6;
@using Modon.Portal.Helpers;
@using PMApp.Core.Helpers;
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@model List<UserRecord>
<style>
    .avatar2 {
        position: relative;
        top: -14px;
        float: right;
        right: -10px;
    }

    .purpleody {
        color: #5A55A3;
    }
</style>
<link href="~/Content/starrr2.css" rel="stylesheet" />
<script src="~/Content/starrr.js"></script>
@if (Model != null && Model.Count() > 0)
{
    foreach (var item in Model)
    {
        if (User.Identity.IsAuthenticated && AuthHelper.GetClaimValue("UserID") != null && item.ID == long.Parse(AuthHelper.GetClaimValue("UserID")))
        {
            <li class="media media-sm  " style="padding-top:5px;padding-left:5px">
                <a class="media-left" href="@Url.Action("ProfileDisplay", "Home", new { userID=item.ID })">
                    <img src="@Url.Content(item.ProfilePictureUrl)" alt="" class="media-object img-thumbnail " style="width:40px;height:40px" />
                    <div class="avatar2 purpleody">
                        <span class="fa-stack ">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-inverse fa-stack-1x arNumbers">@(item.RankOrder > 0 ? item.RankOrder + "" : "...") </i>
                        </span>
                    </div>

                    @*}*@
                </a>
                <div class="media-body">

                    <div class="media-body">
                        <h5 class="media-heading truncate200 text-white">
                            <i class="ion-ios-star"></i><b class="text-success">
                            </b>  @item.NickName
                        </h5>
                        <p><b><b class="arNumbers" style="color:#5A55A3"><i title="Evaluation Points" class="fa fa-line-chart" aria-hidden="true" data-toggle="tooltip" data-placement="right"></i> : @item.Rank</b> <br /><span class="starrr educolor" data-rating="@item.Review" style="pointer-events:none"></span></b> </p>
                        @*@ResourceManager.UIGetResource("points"):@item.Rank |*@
                    </div>
                </div>
            </li>
        }
        else
        {
            <li class="media media-sm ">
                <a class="media-left" href="@Url.Action("ProfileDisplay", "Home", new { userID=item.ID })">
                    <img src="@Url.Content(item.ProfilePictureUrl)" alt="" class="media-object img-thumbnail " style="width:40px;height:40px" />
                    <div class="avatar2 purpleody">
                        <span class="fa-stack ">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-inverse fa-stack-1x arNumbers" >@(item.RankOrder > 0 ? item.RankOrder + "" : "1") </i>
                        </span>
                    </div>
                </a>
                <div class="media-body">
                    <h5 class="media-heading truncate200 text-white">
                        <i class="ion-ios-star"></i><b class="text-success">
                        </b>  @item.NickName
                    </h5>
                    <p><b class="purpleody"><b class="arNumbers"><i title="Evaluation Points" class="fa fa-line-chart" aria-hidden="true" data-toggle="tooltip" data-placement="right"></i> : @item.Rank</b> <br /><span class="starrr educolor" data-rating="@item.Review" style="pointer-events:none"></span></b> </p>

                </div>
            </li>
        }
    }
}
else
{
    <li class="media media-sm" style="background-color:white;border-radius:3%">
        <center>
            <div class="panel panel-success col-md-12">
                <div class="panel-body">
                    <i class="fa fa-5x fa fa-frown-o purpleody"></i>
                    <br />
                    <h4 class="text-black">@ResourceManager.UIGetResource("NoDataAvaialbleForRanking")</h4>
                </div>
            </div>
        </center>
    </li>

}

<script>
    $(document).ready(function () {
        $('[data-toggle=tooltip]').tooltip();
    });
</script>