Modon/Modon.Portal/Controllers/UserWalletController.cs
using Modon.CommonDefinitions.DataContracts;
using Modon.CommonDefinitions.DataContracts.Record;
using Modon.CommonDefinitions.Filters;
using PMApp.Core.CommonDefinitions.Filters;
using Modon.Portal.Helpers;
using Modon.Services;
using PMApp.Core.Services;
using PMApp.Core.CommonDefinitions.DataContracts;
using PMApp.Core.CommonDefinitions.DataContracts.Record;
using PMApp.Core.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMApp.Core.CommonDefinitions;
using PMApp.Modon.DAL6;


namespace  Modon.Portal.Controllers
{
    [Authorize]
    public class UserWalletController : BaseController
    {
        public ActionResult ListUserWallet()
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);

            userWalletRequest.Filter = new UserWalletRequestFilter
            {
                //UserIDList = new List<long> { long.Parse(AuthHelper.GetClaimValue("UserID")) },
            
                    ShowMyManagers = true
            };
           
            var userWalletResponse = userWalletService.DoUserWalletList(userWalletRequest);
            if (Request.IsAjaxRequest())
                    return PartialView("ListUserWalletPartial", userWalletResponse.UserWalletRecords);
            else
                return View(userWalletResponse.UserWalletRecords);

        }
        public ActionResult ListUserWallet2()
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);
            userWalletRequest.Filter = new UserWalletRequestFilter
            {
                ShowMyManagers = true
            };
            var userWalletResponse = userWalletService.DoUserWalletList(userWalletRequest);
                return View(userWalletResponse.UserWalletRecords);

        }

        public ActionResult AddUserWallet()
        {
            var userService = new UserService();
            var userRequest = RequestBuilder.CreateRequest<UserRequest>(User.Identity.Name);
            var userResponse = userService.DoUserListInquiry(userRequest);
            ViewBag.users = userResponse.UserRecords;
            return View();
        }

        [HttpPost]
        public ActionResult AddUserWallet(UserWalletRecord model)
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);
            userWalletRequest.UserWalletRecord = model;
          var  userResponse = userWalletService.DoUserWalletInsert(userWalletRequest);
            if (userResponse.Success.HasValue && userResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(userResponse.Message);

                return RedirectToAction("ListUserWallet");
            }
            else
                SessionHelper.SetFailMessage(userResponse.Message);
            return RedirectToAction("ListUserWallet2");
        }

        [HttpPost]
        public ActionResult EditUserWallet(UserWalletRecord model)
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);
            userWalletRequest.UserWalletRecord = model;
            var userResponse = userWalletService.DoUserWalletUpdate(userWalletRequest);
            if (userResponse.Success.HasValue && userResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(userResponse.Message);
                return RedirectToAction("ListUserWallet2");
            }
            else
                SessionHelper.SetFailMessage(userResponse.Message);
            return RedirectToAction("ListUserWallet2");
        }
        public ActionResult EditUserWallet(long walletID)
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);
            userWalletRequest.Filter = new UserWalletRequestFilter { IDList=new List<long> { walletID } };
            var userResponse = userWalletService.DoUserWalletList(userWalletRequest);

            var userService = new UserService();
            var userRequest = RequestBuilder.CreateRequest<UserRequest>(User.Identity.Name);
            var userResponse2 = userService.DoUserListInquiry(userRequest);
            ViewBag.users = userResponse2.UserRecords;
            return View(userResponse.UserWalletRecords[0]);
        }

        [Authorize]
        public ActionResult DeleteUserWallet(long walletID)
        {
            var userWalletService = new UserWalletService();
            var userWalletRequest = RequestBuilder.CreateRequest<UserWalletRequest>(User.Identity.Name);
            userWalletRequest.UserWalletRecord = new UserWalletRecord { ID = walletID };
            var userResponse = userWalletService.DoUserWalletDelete(userWalletRequest);

            if (userResponse.Success.HasValue && userResponse.Success.Value)
            {
                SessionHelper.SetSuccessMessage(ResourceManager.GetInstance(userWalletRequest.ApplicationID).GetResource("WalletDeletedSuccessfuly"));

                return RedirectToAction("ListUserWallet2");
            }
            else
            SessionHelper.SetFailMessage(userResponse.Message);
            return RedirectToAction("ListUserWallet2");
        }
    }
}

Modon/Modon.Portal/Views/UserWallet/AddUserWallet.cshtml
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6;
@using Modon.CommonDefinitions.DataContracts.Record;
@model UserWalletRecord
@{
    ViewBag.Title = ResourceManager.UIGetResource("AddUserWallet");
}

<div id="content" class="content">
    <h1 class="page-header">
        @ViewBag.Title
    </h1>
    @using (Html.BeginForm("AddUserWallet", "UserWallet", FormMethod.Post, new { id = "formAskQuestion", enctype = "multipart/form-data", @class = "col-md-8 col-md-offset-2" }))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_content">
                        <div class="row demo-container">
                            @if (long.Parse(Modon.Portal.Helpers.AuthHelper.GetClaimValue("UserRoleID")) == ConfigManager.GetUIInstance().SupervisorRoleID)
                            {
                                <div class="form-group">
                                    <label>
إختيار عضو                                    </label>
                                    <div>
                                        @Html.DropDownListFor(model => model.UserID, new SelectList((ApplicationRoleRecord[])@ViewBag.users, "ID", "Name"), @ResourceManager.UIGetResource("ChooseRole"), new { @class = "form-control col-md-7 col-xs-12" })
                                        @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "validation-message" })
                                    </div>
                                </div>
                            }


                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Points")
                                </label>
                                <div>
                                    @Html.TextBoxFor(model => model.Points, new { @class = "form-control col-md-7 col-xs-12", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.Points, "", new { @class = "validation-message" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Attached")
                                </label>
                                <div>
                                    <div class="input-group image-preview">
                                        <input placeholder="" type="text" class="form-control  image-preview-filename" disabled="disabled">
                                        <span class="input-group-btn">
                                            <div class="btn btn-default image-preview-input">
                                                <span class="glyphicon glyphicon-folder-open"></span> <span class="image-preview-input-title input-xs input-inline">@ResourceManager.UIGetResource("Browse")</span>
                                                <input required type="file" class="form-control " name="WebDocumentFile" id="input-file-preview" accept="image/*" onchange="document.getElementById('img-profile').src = window.URL.createObjectURL(this.files[0])" />
                                                <!-- rename it -->
                                            </div>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                </label>
                                <div>
                                    <center>   <img id="img-profile" alt="Product Picture" style="max-height:200px;max-width:200px" src="~/Content/default-product.png" /></center>

                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                </label>
@if (long.Parse(Modon.Portal.Helpers.AuthHelper.GetClaimValue("UserRoleID")) != ConfigManager.GetUIInstance().AdminRoleID)
{
                                <input type="submit" class="btn btn-success btn-block" value="@ResourceManager.UIGetResource("Add")" />
}
else
{
    <center>
        <h1 class="text-danger">غير مسموح لك إضافة أسهم</h1>
    </center>


}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Modon/Modon.Portal/Views/UserWallet/EditUserWallet.cshtml
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6;
@using Modon.CommonDefinitions.DataContracts.Record;
@model UserWalletRecord
@{
    ViewBag.Title = ResourceManager.UIGetResource("EditUserWallet");
}

<div id="content" class="content">
    <h1 class="page-header">
        @ViewBag.Title
    </h1>
@using (Html.BeginForm("EditUserWallet", "UserWallet", FormMethod.Post, new { id = "formAskQuestion", enctype = "multipart/form-data", @class = "col-md-8 col-md-offset-2" }))
{
    <input hidden value="@Model.ID" name="ID" />
    <input hidden value="@Model.UserID" name="UserID" />
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_content">
                        <div class="row demo-container">
                            @if (long.Parse(Modon.Portal.Helpers.AuthHelper.GetClaimValue("UserRoleID")) == ConfigManager.GetUIInstance().SupervisorRoleID && long.Parse(Modon.Portal.Helpers.AuthHelper.GetClaimValue("UserID")) !=Model.UserID)
                            {
                                <div class="form-group">
                                    <label>
                                        إختيار عضو
                                    </label>
                                    <div>
                                        @Html.DropDownListFor(model => model.UserID, new SelectList((ApplicationRoleRecord[])@ViewBag.users, "ID", "Name"), @ResourceManager.UIGetResource("ChooseRole"), new { @class = "form-control col-md-7 col-xs-12" })
                                        @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "validation-message" })
                                    </div>
                                </div>
                            }
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Points")
                                </label>
                                <div>
                                    @Html.TextBoxFor(model => model.Points, new { @class = "form-control col-md-7 col-xs-12", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.Points, "", new { @class = "validation-message" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                    @ResourceManager.UIGetResource("Attached")
                                </label>
                                <div>
                                    <div class="input-group image-preview">
                                        <input placeholder="" type="text" class="form-control  image-preview-filename" disabled="disabled">
                                        <span class="input-group-btn">
                                            <div class="btn btn-default image-preview-input">
                                                <span class="glyphicon glyphicon-folder-open"></span> <span class="image-preview-input-title input-xs input-inline">@ResourceManager.UIGetResource("Browse")</span>
                                                <input type="file" class="form-control " name="WebDocumentFile" id="input-file-preview" accept="image/*" onchange="document.getElementById('img-profile').src = window.URL.createObjectURL(this.files[0])"  />
                                                <!-- rename it -->
                                            </div>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label >
                                </label>
                                <div >
                                    <center>   <img id="img-profile" alt=" Picture"  style="max-height:200px;max-width:200px" src="@(Model.Notes.StartsWith("~")?PMApp.Core.Helpers.UIHelper.ResolveServerUrl(Model.Notes):PMApp.Core.Helpers.UIHelper.ResolveServerUrl("~/Content/default-product.png"))" /></center>

                                </div>
                            </div>
                            <div class="form-group">
                                <label>
                                </label>
                                    <input type="submit" class="btn btn-success btn-block" value="@ResourceManager.UIGetResource("Add")" />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
}
</div>

Modon/Modon.Portal/Views/UserWallet/ListUserWallet.cshtml
@using Modon.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6.EntitiesExtention;
@using PMApp.Core.Helpers;
@using PMApp.Modon.DAL6;
@model UserWalletRecord[]
@{
ViewBag.Title = ResourceManager.UIGetResource("ListUserWallet");
}
@if (Model != null)
{
    <input hidden value="1" name="pageIndex" id="pageIndex" />

    <div class="content">
        <h1 class="page-header">@ViewBag.Title <small></small></h1>
        <div class="row" >
            <div class="panel panel-success" data-sortable-id="ui-media-object-2" style="background:rgba(21, 23, 23, 0.36)">
                <div class="panel-body">
                    <ul class="timeline" id="dvwallet">
                        @foreach (var item in Model)
                        {
                            <li>
                                <!-- begin timeline-time -->
                                <div class="timeline-time" >
                                    <span  class="date text-muted">@PMApp.Core.Helpers.TimeZoneHelper.ToCountryDateTime(item.CreationDate)</span>
                                </div>
                                <!-- end timeline-time -->
                                <!-- begin timeline-icon -->
                                <div class="timeline-icon ">
                                        <a class="bg-white"><i class="fa fa-plus-square fa-fw text-success"></i></a>
                                   
                                </div>
                                <!-- end timeline-icon -->
                                <!-- begin timeline-body -->
                                <div class="timeline-body" style="background:rgba(255, 255, 255, 0.09)">
                                    <div class="timeline-header">
                                        <span>
                                            <i class="fa fa-quote-left fa-fw pull-left"></i>
                                            <b class="text-white">  تم إضافة   </b> <b class="text-white"> @item.Points </b> <b class="text-white"> أسهم بواسطة </b><b class="text-success"> @item.UserFullName </b>
                                            <i class="fa fa-quote-right fa-fw pull-right"></i>

                                        </span>
                                    </div>
                                </div>
                                <!-- end timeline-body -->
                            </li>

                        }
                    </ul>



                </div>
            </div>
        </div>
        <!-- end timeline -->
    </div>
    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">إغلاق</span></button>
                    <h4 class="modal-title" id="myModalLabel">المرفق</h4>
                </div>
                <div class="modal-body">
                    <center> <img src="" id="imagepreview" style="width: 400px; height: 400px;"></center>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
                </div>
            </div>
        </div>
    </div>
}
@BundleConfig.RenderScript("~/ScriptBundles/UserWallet/ListUserWallet")
<script>
    function loadmore()
    {
        var pageIndex=@ViewBag.pageIndex;
        $(".btnloadmore").hide();
        SBSAjax({
            url: ResolveUrl("~/UserWallet/ListUserWallet"),
            type: "post",
            data: {
                pageIndex: $("#pageIndex").val(),
                dBObjectID:@ViewBag.dBObjectID,
            },
            success: function (response) {
                $("#dvwallet").append(response);
                $("#pageIndex").val(parseInt($("#pageIndex").val()) + 1);
            }
        });
    }

</script>

Modon/Modon.Portal/Views/UserWallet/ListUserWallet2.cshtml
@using Modon.CommonDefinitions.DataContracts.Record;
@using PMApp.Core.CommonDefinitions.DataContracts.Record;
@using PMApp.Modon.DAL6;
@model UserWalletRecord[]

<div id="content" class="content">

    <h1 class="page-header">
        @ResourceManager.UIGetResource("UserWallet")
    </h1>
    <div class="row" style="background:rgba(21, 23, 23, 0.36)">
        <div class="panel panel-success" data-sortable-id="ui-media-object-2">

            <div class="panel-body">
                <table class="table data-table">
                    <thead>
                        <tr role="row">


                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                                @ResourceManager.UIGetResource("Points")
                            </th>

                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                                @ResourceManager.UIGetResource("Image")
                            </th>
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                                @ResourceManager.UIGetResource("UserName")
                            </th>
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                                @ResourceManager.UIGetResource("Edit")
                            </th>
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 172px;">
                                @ResourceManager.UIGetResource("Delete")
                            </th>
                        </tr>

                    </thead>

                    <tbody>

                        @if (Model != null && Model.Count() > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr role="row">
                                    <td>
                                       <b>@item.Points</b>
                                    </td>
                                    <td>
                                        <img  onclick="PreviewImg(this);" style="cursor:pointer" id="myImg" width="30" height="30" src="@(item.Notes.StartsWith("~")?PMApp.Core.Helpers.UIHelper.ResolveServerUrl(item.Notes):PMApp.Core.Helpers.UIHelper.ResolveServerUrl("~/Content/default-product.png"))" />
                                    </td>
                                    <td>
                                       <b>@item.UserFullName</b> 
                                    </td>
                                    <td>
                                        <a href="@Url.Action("EditUserWallet", new { walletID = item.ID })" class="btn btn-success btn-sm">@ResourceManager.UIGetResource("EditUserWallet")</a>
                                    </td>
                                    <td>
                                        <a href="#" onclick="DeleteUserWalletCheck('@item.UserFullName','@item.ID')" class="btn btn-danger btn-sm">@ResourceManager.UIGetResource("Delete")</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4">
                                    <center><i class="fa fa-5x fa-info-circle text-warning"></i></center>
                                    <br />

                                    <center> <h4 class="text-black">@ResourceManager.UIGetResource("NoconfigssHasBeenAdded")</h4></center>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">الصورة</h4>
            </div>
            <div class="modal-body">
                <center> <img src="" id="imagepreview" style="width: 400px; height: 400px;"></center>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/UserWallet/ListUserWallet.js"></script>
<script>
    function PreviewImg(e) {
        $('#imagepreview').attr('src', $(e).attr('src'));
        $('#imagemodal').modal('show');
    }

</script>